### ISSUE TITLE
Ayuda con curso de Udemy de blog personal django2

### ISSUE THREAD

**Issue by jhonescuba** [hektorprofe/curso-django-udemy#1]
Buen día Hector, siguiendo tu tutorial me encontré con un problema y veo que en el curso vario tienen el mismo inconveniente. en el video 19 al finalizar las indicaciones de las etiquetas salen errores y los estilos no se cargan como deberia.

en los comentarios del curos se muestran las imagenes. 

https://img-a.udemycdn.com/redactor/raw/2020-04-16_22-24-39-b1a578aa52e83fbdcc8199036a30e34d.PNG?-6XtAkjzXwNtgP4QHN_lnCCKxRcKJyNNjbMEGqTPmzcyfY7IUdi6-EanNTdCpPKaEy8frLSo1Gxh6z1QvZ3yru0lMcB2QocmSdVsuirft3P04b5DbcpKHD0iJJ8CT9KK90le2bnXty9TVn7hLQSf4NLzkY3nuSyDttS3LbPLbXe2IArL

Por favor me gustaria ponerme en contacto contigo y poder solucionar el tema y asi poder ayudar a los demas que tienen el mismo inconveniente.

Gracias y quedo atento.

**Comment by hcguz** [comment]
Hola @jhonescuba , necesito replicar el error para saber más, puedes comprimir tu proyecto en un .zip y enviarmelo al correo hey@hektor.dev ? Podemos seguir comentando el asunto por email.

**Comment by jhonescuba** [comment]
Gracias Hector.
Adjunto el zip con el proyecto.en drive por temas de las extensiones no me
deja adjuntarlo por este medio.

https://drive.google.com/drive/folders/1bnnlB7aFs9LG2vXykgTEAvOxyIm083WR?usp=sharing


Te voy a mostrar un poco mi panorama.

[image: image.png]

[image: image.png]

[image: image.png]

En el VS Code me marca esos mensajes de error y la pagina se muestra de la
siguiente manera en todos los enlaces (home, about, portfolio y contact ).


[image: image.png]

Gracias de antemano y quedo atento a cualquier comentario.

Feliz día.
Cordialmente,
Jhon Esteban Cuartas Báez.

**Comment by hcguz** [comment]
Hola, he revisado el código, tienes un par de errores en la codificación del template:

Línea 17:     
`<link href="{% static 'core/css/clean-blog.min.css" rel="stylesheet' %}">`

Debe ser:
`<link href="{% static 'core/css/clean-blog.min.css' %}" rel="stylesheet">`

Y línea 51:

`<header class="masthead" style="background-image: url('{% static 'core/img/home-bg.jpg' %}")">`

Debe ser:

`<header class="masthead" style="background-image: url('{% static 'core/img/home-bg.jpg' %}')">`

**Comment by jhonescuba** [comment]
Si Sr,

Tiene ud toda la razón. Ya con esas modificaciones me funcionó.

Voy a continuar con las demás lecciones a partir de allí. y a comentar a
las personas del curso que tienen el mismo inconveniente.,

Mil y mil gracias por tu colaboración, un abrazo desde Colombia y muy buen
curso.


[image: image.png]

**Comment by hcguz** [comment]
Perfecto cierro el ticket
